# Generated by Django 4.2.11 on 2024-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
